# Generated by Django 5.2.11 on 2026-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['titulo']},
        ),
    ]
