# Generated by Django 5.2.11 on 2026-02-17 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_documento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre']},
        ),
    ]
