# Generated by Django 5.2.11 on 2026-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_tipodocumento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Área / Departamento', 'verbose_name_plural': 'Áreas / Departamentos'},
        ),
    ]
