# Generated by Django 5.2.11 on 2026-02-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_area_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('organigrama', 'Organigrama'), ('tabla_aplicabilidad', 'Tabla de Aplicabilidad')], max_length=30, unique=True, verbose_name='Tipo de Documento')),
                ('archivo_pdf', models.FileField(upload_to='destacados/', verbose_name='Archivo PDF')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Destacado',
                'verbose_name_plural': 'Documentos Destacados (Organigrama/Tabla)',
            },
        ),
    ]
